---
# This workflow runs on every push to 'main' cuz of cache scoping peculiarities.
# For more info see https://github.com/AllanChain/blog/issues/98.
name: Build PyOxidizer and cache it
on:
  push:
    branches:
    - main
defaults:
  run:
    shell: bash
jobs:
  generate-pyox-cache:
    env:
      PYOX_VERSION: '0.7.0'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Rust toolchain
      id: install-rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    # From: https://github.com/denoland/deno/blob/71a9879/.github/workflows/ci.yml
    - name: Configure cargo data directory
      run: echo ::set-env name=CARGO_HOME::$HOME/.cargo
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: >-
          cargo-cache-${{ runner.os }}-${{ steps.install-rust.outputs.rustc_hash }}-${{ env.PYOX_VERSION }}_5
    - name: Install PyOxidizer
      run: |
        cargo install --version $PYOX_VERSION pyoxidizer
